{
  "formatVersion": "1.1",
  "component": {
    "group": "com.arthenica",
    "module": "ffmpeg-kit-full",
    "version": "6.0-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.arthenica",
          "module": "smart-exception-java",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-kit-full-6.0-2.aar",
          "url": "ffmpeg-kit-full-6.0-2.aar",
          "size": 53165315,
          "sha512": "5a62b1060a77f4cb3c91b8394e4658ebb013a853e7432ad29fabcd5eca4496d524fa82e29ebf92fe1aefb4f09e74c88adba3dc628f2d237d214de279194da1bd",
          "sha256": "5a37a58cf6deef4eea5a598f3cf9a2c2d642e9bbccb231d6d3e83d152b70b9ea",
          "sha1": "2ee9d228d13f4766aa97ba26d8ade05395abe0c8",
          "md5": "d0a3b2d70844ca97fa4d5ba8721b331a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.arthenica",
          "module": "smart-exception-java",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-kit-full-6.0-2.aar",
          "url": "ffmpeg-kit-full-6.0-2.aar",
          "size": 53165315,
          "sha512": "5a62b1060a77f4cb3c91b8394e4658ebb013a853e7432ad29fabcd5eca4496d524fa82e29ebf92fe1aefb4f09e74c88adba3dc628f2d237d214de279194da1bd",
          "sha256": "5a37a58cf6deef4eea5a598f3cf9a2c2d642e9bbccb231d6d3e83d152b70b9ea",
          "sha1": "2ee9d228d13f4766aa97ba26d8ade05395abe0c8",
          "md5": "d0a3b2d70844ca97fa4d5ba8721b331a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ffmpeg-kit-full-6.0-2-sources.jar",
          "url": "ffmpeg-kit-full-6.0-2-sources.jar",
          "size": 52797,
          "sha512": "e2b5124008aa5438c3477ae1d1f5b1e9d3b0f13f513e1b6d458c3ec5d25a52400a5abd5bc1535929bfff042625a7ebd4281fc3f93e95261f6a55dfe0b28993cb",
          "sha256": "0a3a53d0bb9fa75341c610fefc54590e99f735e60d56916a3509ac3051ac3b00",
          "sha1": "767e676594e638b42e22aceedce743da8eab9a3f",
          "md5": "a866d207fad8b7ceb28e5d46d407189d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ffmpeg-kit-full-6.0-2-javadoc.jar",
          "url": "ffmpeg-kit-full-6.0-2-javadoc.jar",
          "size": 415368,
          "sha512": "e554e2426a85487deccb5f40c5bb5e75c6e2c8b8f2c357107db1210b0d83284bc170a2a60fae0f2075398faca0bd6c5fd3d9edefb539407da9bc65e0554cef0b",
          "sha256": "4a4146e2a869d4ee544f6b141ad062838f7625b2fabb60162bc3b6548d1018fc",
          "sha1": "8ba949bc28219479e7c2385e598d1cb2452df75e",
          "md5": "a8a63c271cad04006c88d6367a771797"
        }
      ]
    }
  ]
}
